### ISSUE TITLE
Add additional database fields

### ISSUE THREAD

**Issue by Bertware** [oSoc15/educal#13]
To be added:

User:
- verified (bool) // user is representative of verified organisation

School:
- Slug
- URL
- Address
- Phone
- Mail
- Active

**Comment by Bertware** [comment]
To add:
Appointment:
- color

**Comment by thgh** [comment]
Calendar:
- color/hue
- PRODID

Appointment
- label color/text color
- image
- person
- location/address/place/latlong
- summary/description
- PRODID
- alarm
- status: cancelled
- category

inspiration from https://www.nttdocomo.co.jp/english/service/developer/make/content/iconcier/scheduler/format/

**Comment by Bertware** [comment]
Resolved in commit d9ca3a38569e677ce90e9d915426d95425227e69

![database_newfields](https://cloud.githubusercontent.com/assets/1094793/8668597/05c6d932-2a0d-11e5-8bd8-55d60da1b4a5.png)
