### ISSUE TITLE
As a registered person, I can log in with my e-mail and password

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#16]
As a registered person, I can log in with my e-mail and password.
- [x] Error handling: friendly message that un/pass is incorrect

**Comment by Bertware** [comment]
New design implemented, validation & feedback still to do (commit 600c96c32d27c473cab6afa0efaf7a11ca4e59f8)

**Comment by thgh** [comment]
Ready as of d512f9c

**Comment by xavez** [comment]
@thgh when I click login, the popover disappears, so I never see the error message. We should probably use HTML5 validation to make sure the form doesn’t submit when empty.

**Comment by xavez** [comment]
Seemed to have been a deployment server issue. All works now. Great!
