### ISSUE TITLE
As a parent, I can select which calendar I want to hide/show

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#19]
- [x] UI design
- [x] Multi-select in front end
- [x] Dropdown SVG arrow

**Comment by brucevansteenwinkel** [comment]
<img width="123" alt="schermafbeelding 2015-07-14 om 16 07 08" src="https://cloud.githubusercontent.com/assets/4647210/8675116/5ca34b8e-2a42-11e5-9c2d-3dfa17281514.png">

**Comment by xavez** [comment]
@brucevansteenwinkel can you give all the states? Selected, not selected, focused with keyboard etc?

**Comment by brucevansteenwinkel** [comment]
<img width="139" alt="schermafbeelding 2015-07-14 om 16 40 08" src="https://cloud.githubusercontent.com/assets/4647210/8675978/fbeca77c-2a46-11e5-9b09-981087a83b09.png">

Default: grey overlay, color shows when hovered, color stays vibrant when checked
Klas just regular checkbox

**Comment by xavez** [comment]
@brucevansteenwinkel not sure about @thgh but I find that pretty vague as a description :D. Could help to have an actual design per state for UI elements. Similar to: ![Image of UI elements](http://f.cl.ly/items/3M473K3S1K3H3Z3g1d17/Image%202015-07-14%20at%205.15.40%20p.m..png)

**Comment by xavez** [comment]
Still has some display bugs, but will report in separate issue. SVG arrows look nice! :+1: ;)
