### ISSUE TITLE
As a person, I can see which events relate to which calendar when multiple calendars are active

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#20]
- [x] Design with colours 
- [x] Make sure colour blind ppl can see this
- [x] Implement front-end
- [ ] Colors

**Comment by brucevansteenwinkel** [comment]
<img width="639" alt="schermafbeelding 2015-07-14 om 16 01 21" src="https://cloud.githubusercontent.com/assets/4647210/8674967/8d170bda-2a41-11e5-8131-589c424c670b.png">

Uploaded the svg files in slack

**Comment by xavez** [comment]
Todo @brucevansteenwinkel : check kleurtjes / patronen / iconen / . . .

**Comment by brucevansteenwinkel** [comment]
Filed uploaded to slack

**Comment by thgh** [comment]
Groen: 34ce45
Lichtblauw: 3a8bce
Rood: c13838
Munt: 2cdbca
Geel: e5c12c
Paars: 7548cc
Oranje: e08a00
Roos: d66ae5

**Comment by xavez** [comment]
@brucevansteenwinkel can you check if the colours are correct by your design on http://178.62.152.244? When they’re good, you can comment on and close the issue.

**Comment by brucevansteenwinkel** [comment]
Checked, they're correct!
