### ISSUE TITLE
As an editor, I can add an event on one day by clicking that day

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#21]
Two more minor issues.
- [x] Whitespace between arrow in “Tijd” and border-bottom of “Title” 
- [x] Missing margin under in Calendar dropdown

See screenshot: http://c.xvr.io/image/2m0H2U2e2t0p

**Comment by brucevansteenwinkel** [comment]
<img width="899" alt="schermafbeelding 2015-07-14 om 15 40 52" src="https://cloud.githubusercontent.com/assets/4647210/8674510/af4bd5f8-2a3e-11e5-8441-2c6d7de735c2.png">

Addition to day selection

**Comment by xavez** [comment]
Two more minor issues.
- [x] Whitespace between arrow in “Tijd” and border-bottom of “Title” 
- [x] Missing margin under in Calendar dropdown

See screenshot: http://c.xvr.io/image/2m0H2U2e2t0p

**Comment by xavez** [comment]
Much better! :-).
