### ISSUE TITLE
As an editor, I can delete an event

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#22]

**Comment by brucevansteenwinkel** [comment]
<img width="555" alt="schermafbeelding 2015-07-16 om 09 14 25" src="https://cloud.githubusercontent.com/assets/4647210/8717368/21548cdc-2b9b-11e5-969e-4668f9c1db5b.png">

**Comment by thgh** [comment]
This works as it should

**Comment by xavez** [comment]
One question: what if there is an error? e.g. an event cannot be deleted because of a server or database connection issue? Is there a way to show the user an error message?

@thgh feel free to answer and re-assign to me when answered.

**Comment by thgh** [comment]
Currently there is no way to show input errors, connection errors or server errors.

My current plan is to start with html5 validation for input errors.
And other errors will be rendered with alertify.js or notify.js

**Comment by xavez** [comment]
Okay, excellent, added new user story to backlog for error messaging. This works as intended.
