### ISSUE TITLE
As an editor, I can see all the calendars in my organisation (read only)

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#24]
- [ ] UI: list view
- [x] Back-end: list view
- [x] Front-end: list view

**Comment by xavez** [comment]
Design: make clear that some calendars are read only.

**Comment by brucevansteenwinkel** [comment]
Discussed with Thomas, there is a read-only view for people who can't edit an event. People who can dit go immediately to the edit / add view
<img width="946" alt="schermafbeelding 2015-07-27 om 14 42 57" src="https://cloud.githubusercontent.com/assets/4647210/8906288/af55a536-346d-11e5-85e7-fb874f3918b1.png">

**Comment by xavez** [comment]
Okay, assigned to @thgh :-)

**Comment by xavez** [comment]
Has some bugs, but basic idea works, will post bugs as separate issues.
