### ISSUE TITLE
As an editor, I can edit all events on the calendars that I have explicit access to

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#25]
Also see #23

**Comment by brucevansteenwinkel** [comment]
<img width="839" alt="schermafbeelding 2015-07-14 om 14 16 23" src="https://cloud.githubusercontent.com/assets/4647210/8672909/e1e3c4be-2a32-11e5-81ca-d08451b33548.png">

Tell me if I'm doing something wrong, or if you have other ideas let me know

**Comment by Bertware** [comment]
backend (CRUD) is available for this operation

**Comment by xavez** [comment]
@brucevansteenwinkel I like this, but I do think we will need to decide at some point whether everything will be live editing or whether we need save actions everywhere.

In this particular case, it’s not so clear what to do after I’m done editing for instance. I think it’s mostly because a real modal like this (with dark grey overlay) usually has close / save buttons. Maybe try to go for a popout / popover approach rather than a modal? See https://dribbble.com/search?q=popout and https://dribbble.com/search?q=popover

**Comment by Bertware** [comment]
AJAX request to API should include calendar Id, except for that, everything should be working
