### ISSUE TITLE
As a parent, I can read about how to add a calendar to my device

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#31]

**Comment by xavez** [comment]
@Bertware, assigning this one to you. Discuss with @thgh who will pick this up. We really need the help page @brucevansteenwinkel designed, otherwise, it will all have been for nothing :D.

This help page is one of the key things of the app! Really important to get this in there ;).

**Comment by Bertware** [comment]
Started working on this this afternoon, talked with @thgh already, I know how to implement it now :)

**Comment by Bertware** [comment]
Works!
