### ISSUE TITLE
As a user, I can register an account on the educal website

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#35]
- [x] “Log hier in” link looks off: http://c.xvr.io/image/2q2n351r3h0H discuss with @brucevansteenwinkel
- [x] School name is either saved or rendered without spaces, see: http://c.xvr.io/image/0q2z0J110G11
- [x] Make the error messages more friendly: “Vergeet je _fieldname_ niet in te vullen” 
- [x] Link “Start nu gratis” button on homepage to `/register`

**Comment by Bertware** [comment]
See #36 .
A user account is created when creating an organisation. Creating an account without creating a new organisation is not possible (right now). Creating users for a school should be done by school admins

**Comment by Bertware** [comment]
Registration works. Feedback needs to be styled. Can be tested at http://178.62.152.244/register

**Comment by xavez** [comment]
- [x] Log hier in link looks off: http://c.xvr.io/image/2q2n351r3h0H maybe discuss with @brucevansteenwinkel 
- [x] School name is apparently either saved or rendered without spaces, see: http://c.xvr.io/image/0q2z0J110G11
- [ ] We need to make the error messages more friendly, maybe @dorienmarinus or @brucevansteenwinkel can have a look and rewrite these: http://c.xvr.io/image/1w2H0S3M132g

**Comment by ghost** [comment]
Voorstellen:
- "voornaam" is nog niet ingevuld
- vergeet je voornaam niet in te vullen
- je moet je voornaam invullen voor je verder kan
- oeps, je bent je voornaam vergeten in te vullen
- je bent je voornaam vergeten in te vullen, shame on you
- I aint working without a voornaam

**Comment by xavez** [comment]
@Bertware issue description at the top updated.

**Comment by xavez** [comment]
Almost there, just one tiny tweak to the copy: 

“Vergeet **je** _fieldname_ niet in te vullen”

**Comment by xavez** [comment]
Aaaaaaaand close that sucker!

<img src="http://38.media.tumblr.com/42856c2e73c51ab9dfd0621bb5f9f190/tumblr_mi2sr4NPdK1rjf0fxo1_250.gif" />
