### ISSUE TITLE
Document how to set up the project in README.md

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#39]
Documentation should contain a small guide of how to set up the project locally, and on a server.
Minimal is good enough for now, but make sure to list all the necessary steps

e.g. “install bower” with a link to the bower documentation is good enough. But you should definitely mention that you need to install bower.

**Comment by thgh** [comment]
Some content to include in README:

## Stack
- FullCalendar http://fullcalendar.io
- Laravel
- jquery for public view
- angularjs for admin view

Development dependencies:
- bower
- grunt
- sass
- uglify

## Installation

### nginx configuration

```
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/educal.gent.be;
    index index.php index.html index.htm;
    server_name educal.gent.be;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```

### Apache configuration

todo

#### Install dependencies

```
composer install
php artisan migrate --seed

npm install
npm install -g bower grunt-cli
bower install
grunt
```

### Laravel

Create config file and insert MySQL database info

```
cd /var/www/educal.gent.be
cp app/config/database.php app/config/local/database.php 
nano app/config/local/database.php
```

**Comment by xavez** [comment]
Documentation is good now. Just did a set-up from 0. Good job.
