### ISSUE TITLE
Update data structure

### ISSUE THREAD

**Issue by Bertware** [oSoc15/educal#4]
We will be using our own table to store groups (aka classes/calendars). To prevent confusion, groups will be called calendars, and groups will be called roles.
## Add table calendars
- [x] Add to database migrations
- [x] Add model
- [x] Add relations (linked to users)
- [x] Update code to use new structure
## Rename table groups

In order to prevent confusion, the 'groups' table should be renamed to roles. This requires changes to both the database and the source code.
- [x] Database migration: Rename groups table to 'roles'
- [x] Database migration: Rename pivot table (users_groups) to 'users_roles'
- [x] Rename 'group' model to 'role', and clean up unneeded code
- [x] Alter config (app/config/packages/sentry/config.php) to match above changes

**Comment by coreation** [comment]
You'll need to alter code (or configuration) to the cartalyst/sentry package for this, so make sure you're not doing unnecessary work here. Not sure why you're choosing to store classes and calendars in "groups"? Can you elaborate?

**Comment by Bertware** [comment]
The necessary changes to Sentry are made in the config file. Right now, a group contains users, each user having its own set of permissions. 
The new structure would divide these groups in roles and groups.
Roles are used for permissions, managed by Sentry, which treats them as the default 'groups' table. Roles can be superadmin, admin (school) and teacher (normal user).
'Groups' or 'calendars', which group events, contain specifications like name, color, .... Multiple users (teachers) can belong to a calendar, multiple calendars can belong to one user (making use of a pivot table)

**Comment by Bertware** [comment]
Controllers to be refactored:
- [x] CalendarController
- [x] CalendarViewController
- [x] HomeController
- [x] ICalCalendarController
- [x] PdfCalendarController
- [x] SchoolController
- [x] UserController
