### ISSUE TITLE
Add a button to add an event

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#42]
We might need a button to add an event from the sidebar (not on the calendar)

Less priority because people eventually find how to add an event.

**Comment by Bertware** [comment]
Added button, just needs to be hooked in to javascript. Button only visible when logged in.

**Comment by mietcls** [comment]
The button that says “voeg event toe”, it’s just as prominent as export. Make them switch places and make the export button a little less prominent (a secondary button), so it won't stand out so much.

This is an example, but ask @brucevansteenwinkel for a secondary button.

![schermafbeelding 2015-07-29 om 17 14 29](https://cloud.githubusercontent.com/assets/1572885/8961430/6a8356b6-3615-11e5-9fc8-d605ea9ce57b.png)

**Comment by Bertware** [comment]
duplicate with #51 ?

**Comment by xavez** [comment]
Fixed. Great!
