### ISSUE TITLE
Error handling for when add event is empty (same as login)

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#43]
When you click “Toevoegen” to add an event, and the title is empty, there is no feedback. There needs to be feedback similar to the feedback on the login page.

Highlight field title and add a line that says “Titel vereist"

**Comment by thgh** [comment]
Fixed

**Comment by xavez** [comment]
Almost. One more thing: remove the warning styling when the user starts typing in the input field :-).

**Comment by xavez** [comment]
Hooray!
