### ISSUE TITLE
Tweak multiple event drag behaviour

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#45]
When dragging from 1-3 august, the event popup shows 1 aug 00:00 to 4 aug 00:00. Expected behaviour is 1 aug 00:00 to 3 aug 23:59

See: http://c.xvr.io/image/3Y3p0L033317

**Comment by mietcls** [comment]
Tweak: It should just say "all day" instead of the hours. If an event lasts the whole day, it shouldn't be specified.

**Comment by mietcls** [comment]
This issue has been split up in #48 and #49
