### ISSUE TITLE
List of hours: per half hour in stead of per hour

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#46]
The list of hours now has increments of 1 hour, increments of 30 minutes would be useful according to test people.

**Comment by Bertware** [comment]
Can be tested by adding or editing an event

**Comment by xavez** [comment]
Still has a quirky bug where two times are selected (and not the correct ones):

<img width="380" alt="schermafbeelding 2015-07-29 om 14 48 15" src="https://cloud.githubusercontent.com/assets/400335/8957767/f0511aea-3600-11e5-95f8-ddada00f8943.png”>

Test:

- Create event
- Change start date to 11:30 via dropdown
- Change time again, see that 12:00 and 12:30 are selected

**Comment by xavez** [comment]
Still has a quirky bug where two times are selected (and not the correct ones). Test:
- Create event
- Change start date to 11:30 via dropdown
- Change time again, see that 12:00 and 12:30 are selected

<img width="380" alt="screen" src="https://cloud.githubusercontent.com/assets/400335/8957808/4757bd58-3601-11e5-85f8-7b054a29f335.png">

**Comment by xavez** [comment]
Yeey, that works perfectly now!
