### ISSUE TITLE
Multiple day event: hours

### ISSUE THREAD

**Issue by mietcls** [oSoc15/educal#49]
The hours shouldn't be displayed, we should only show "Hele dag" with a checkbox. If this checkbox is unchecked, the hours can be 08:00 (first day) to 09:00 (last day). (http://c.xvr.io/image/3Y3p0L033317)

See #45

**Comment by thgh** [comment]
Fixed

**Comment by mietcls** [comment]
Could you look at the hours? It still starts at 00:00 first day and ends at 23:59 last day instead of starting at 08:00 first day and ending 09:00 last day (it's more consistent behavior, it has the same behavior with a single day)
