### ISSUE TITLE
As an admin, I can add new users to my organisation

### ISSUE THREAD

**Issue by Bertware** [oSoc15/educal#50]
As an admin, I can add a new (non-existent) user to my school. The user account for this user will be created.
- [x] Backend
- [x] Frontend
- [x] Password reset
- [x] Configure mail on test server

**Comment by Bertware** [comment]
Everything should be implemented now, except for the "send password" button in frontend (minor stuff) :)

**Comment by Bertware** [comment]
To do: Configure mail on test server

**Comment by thgh** [comment]
Current status, we need a reliable smtp server
"Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
 535 5.7.8 https://support.google.com/mail/answer/14257 r8sm3781644wiz.5 - gsmtp
 ""

**Comment by Bertware** [comment]
Works!
Correct mail configuration is essential though
