### ISSUE TITLE
Make log in button more prominent

### ISSUE THREAD

**Issue by mietcls** [oSoc15/educal#51]
To avoid confusion about your access rights:

When visiting the calendar when you are not logged in, the login button should be more prominent, because it is a call to action.

![schermafbeelding 2015-07-29 om 17 24 37](https://cloud.githubusercontent.com/assets/1572885/8961645/ad427274-3616-11e5-894a-f346e420106c.png)

**Comment by xavez** [comment]
Works. Excellent.
