### ISSUE TITLE
When I add an event to a calendar, that calendar should be activated.

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#53]
When I add an event to a calendar that is not currently active, it just seems as if the event disappears. The event does save, but my calendar is not activated, which makes it feel broken.

When I add an event to a calendar, that calendar should be activated.

**Comment by xavez** [comment]
This works for admin, but somehow doesn’t work for editor, can you check? Might have something to do with the db / perms?

**Comment by thgh** [comment]
It only works for lowest level calendars. Should all subcalendars open when adding an event to the 4th year?

**Comment by xavez** [comment]
Yes! :-)

An option is adding a checkbox to toggle “all calendars” 

## 1e jaar
- [ ] Alle groepen
- [ ] 1A
- [ ] 1B

## 2e jaar
- [x] Alle groepen
- [x] 2A
- [x] 2B
- [x] 2Z

**Comment by xavez** [comment]
Not quite as I imagined, but works quite well, closing it :-).
