### ISSUE TITLE
Create event: not all fields should be required

### ISSUE THREAD

**Issue by xavez** [oSoc15/educal#57]
Only the title field should be required when creating an event

<img width="381" alt="pop" src="https://cloud.githubusercontent.com/assets/400335/8969012/085c9584-3641-11e5-9748-550814397d0d.png">

**Comment by thgh** [comment]
This is required server side

**Comment by Bertware** [comment]
Server side only requires calendar_id, start,end and title

**Comment by Bertware** [comment]
To be tested: how does an event without description or location show up in readonly mode? can be tested by logging out

**Comment by xavez** [comment]
@Bertware apparently it does’t. Check out:
- http://178.62.152.244/osoc
- Toggle klas 1B on
- Click on the “Test again” event on 16 july

**Comment by Bertware** [comment]
The popup not opening seems to be a general issue, see #60

**Comment by Bertware** [comment]
Popups are now shown, but the location bar etc is just empty. Placeholder text ('no location') or icons?

**Comment by xavez** [comment]
@Bertware is it possible to remove the entire p?

**Comment by xavez** [comment]
Great!
