### ISSUE TITLE
Copy onepager

### ISSUE THREAD

**Issue by ghost** [oSoc15/educal#58]
@Bertware 
The onepager still needs some changes on the copy
Check slackmessage Bruce!
- Schoolkalender is one word
- at login: Email is written as e-mail
- vilvoorde moet weg, vervangen worden door school vanuit Gent
- 'hoe werkt het' in upper menu moet 'wat is educal' worden
- educal met hoofdletter?

**Comment by xavez** [comment]
@dorienmarinus should be fixed. Wefwesh.

**Comment by xavez** [comment]
Alright, changed educal to Educal, everything should be fixed now @dorienmarinus

**Comment by xavez** [comment]
Closing this, considering it fixed.
