### ISSUE TITLE
Events always saved as allday even when not checked

### ISSUE THREAD

**Issue by Bertware** [oSoc15/educal#59]
Even when unchecking allday, the event is saved as an allday event

**Comment by xavez** [comment]
@Bertware do you expect me to do something? :-)

**Comment by xavez** [comment]
@Bertware this seems to be working now, but I’m not sure I ever saw the issue . . . Assigning it to you, if it works for you, close it! ;).

**Comment by Bertware** [comment]
Fixed :)
