### ISSUE TITLE
As an admin, I can remove editors from my organisation

### ISSUE THREAD

**Issue by Bertware** [oSoc15/educal#72]
Steps to reproduce:
- Login as admin
- Go to dashboard > medewerkers

There is no option to remove users.

Suggested fix;
Add column with remove buttons.
Users can be completely removed since they're always linked to only one school.
Backend functionality is already implemented by a DELETE request to api/1/users/{id}.

**Comment by tthoeye** [comment]
Working on this. @Bertware can you assign me?

**Comment by Bertware** [comment]
Can't assign because you're not in oSoc15, but I'll set it to working :)

**Comment by tthoeye** [comment]
Perfect :)
