### ISSUE TITLE
Cannot select calendars on the overview page

### ISSUE THREAD

**Issue by tthoeye** [oSoc15/educal#74]
I'm getting `Uncaught TypeError: $(...).fullCalendar is not a function` whenever selecting a calendar in the sidebar. Probably JS confusion.

**Comment by Bertware** [comment]
Are you using educal.gent.be or are you running a test version yourself? 
Both latest master (on vagrant) and the deployed version are working for me.

What's the name of the calendar you're trying to toggle?

**Comment by tthoeye** [comment]
Hi Bert, I am testing on a self deployed version here: http://educal.open.gent. It had to do with including jQuery twice. Appearantly it was compiled into app.js. When I leave that out it works for me, see https://github.com/tthoeye/educal/commit/416ac1199149a6c116ce14acb8a6260164905a51

**Comment by Bertware** [comment]
It's really weird, I just checked the entire repo for app.js, and I can't find it anywhere (it doesn't get compiled either). I do remember removing that file since it was created during oSoc14, and got obsolete in oSoc15. Anyway, removing the app.js include was correct, and the issue's fixed.

**Comment by tthoeye** [comment]
\o/ Thanks for checking! I think it did get compiled somewhere but I'm completely new to this Laravel / Bower / Grunt workflow so it's very difficult for me to point out where :)

**Comment by Bertware** [comment]
The only compiled file is production.js (also minified to production.min.js), no trace of app.js. It's correct like this as app.js is not needed/used. Maybe it got compiled by a script from the oSoc14/Code9000 repo.
Marking this as fixed!
