### ISSUE TITLE
Cannot add users to my organization (403)

### ISSUE THREAD

**Issue by tthoeye** [oSoc15/educal#78]
Relates to story #50 

I'm having trouble adding users to my organization, POST to /api/1/users returns 403 (Permission Denied)

**Comment by dmadigipolis** [comment]
Hi, I tried to add a new user via educal.open.gent. But when I click the button 'Bewaren', nothing happens, nothing is saved (Chrome/win7) No messages given.

**Comment by tthoeye** [comment]
Thx, I tried with chrome/win but have no problem adding a user. Could you please provide some details (username, school and password) so I can try to reproduce. Also, it would help if you can provide us with the console output (ctrl-shift-i) in Chrome

**Comment by dmadigipolis** [comment]
Hi Thimo,

Ondertussen heb ik de fout al gevonden. Ik probeerde een (test-)user aan te maken met een mailadres dat hij al kende voor een andere school.
Dat is dus correct gedrag, alleen had ik graag een boodschap gehad om dit te melden op het scherm.

Bijgevoegd een hele lijst van defects die ik gevonden heb tijdens mijn eerste testen.

Mvgr,
Dominic

Van: tthoeye [mailto:notifications@github.com]
Verzonden: donderdag 17 september 2015 15:52
Aan: oSoc15/educal
CC: Maes Dominic
Onderwerp: Re: [educal] Cannot add users to my organization (403) (#78)

Thx, I tried with chrome/win but have no problem adding a user. Could you please provide some details (username, school and password) so I can try to reproduce. Also, it would help if you can provide us with the console output (ctrl-shift-i) in Chrome

**Comment by dmadigipolis** [comment]
Heel erg bedankt Dominic,
Ik hoop dat je hier niet te veel tijd in hebt moeten steken.

Ik wil zeker nog eens door deze uitgebreide lijst gaan, maar het zou wel handig zijn als je de issues zou rapporteren in GitHub zoals je deed met onderstaande. Liefst ook het onderscheid maken tussen bugs (dit werkt niet) en improvements (dit kan beter) of extra features (dit mist nog).

Ik heb ze voorlopig even op Google Docs gezet voor het gemak https://docs.google.com/spreadsheets/d/1Nnt0RJsqNnw-cmT8Hnu6aZd1-FMUUoAvHR_hPtmkrYI/edit?usp=sharing

Vriendelijke groeten,
Thimo

---

Van: Maes Dominic
Verzonden: donderdag 17 september 2015 16:02
Aan: oSoc15/educal
CC: Bernaert Ann; Thoeye Thimo
Onderwerp: RE: [educal] Cannot add users to my organization (403) (#78)

Hi Thimo,

Ondertussen heb ik de fout al gevonden. Ik probeerde een (test-)user aan te maken met een mailadres dat hij al kende voor een andere school.
Dat is dus correct gedrag, alleen had ik graag een boodschap gehad om dit te melden op het scherm.

Bijgevoegd een hele lijst van defects die ik gevonden heb tijdens mijn eerste testen.

Mvgr,
Dominic

Van: tthoeye [mailto:notifications@github.com]
Verzonden: donderdag 17 september 2015 15:52
Aan: oSoc15/educal
CC: Maes Dominic
Onderwerp: Re: [educal] Cannot add users to my organization (403) (#78)

Thx, I tried with chrome/win but have no problem adding a user. Could you please provide some details (username, school and password) so I can try to reproduce. Also, it would help if you can provide us with the console output (ctrl-shift-i) in Chrome

�

**Comment by dmadigipolis** [comment]
Hoi Thimo, 

Ik zie dat Bertware al wat bevindingen in Github heeft gestoken/opgelost. 
Is de nieuwe versie beschikbaar op educal.open.gent?

D.

-----Oorspronkelijk bericht-----
Van: Thoeye Thimo 
Verzonden: donderdag 17 september 2015 16:24
Aan: Maes Dominic; oSoc15/educal
CC: Bernaert Ann; Rosseau Bart
Onderwerp: RE: [educal] Cannot add users to my organization (403) (#78)

Heel erg bedankt Dominic,
Ik hoop dat je hier niet te veel tijd in hebt moeten steken.

Ik wil zeker nog eens door deze uitgebreide lijst gaan, maar het zou wel handig zijn als je de issues zou rapporteren in GitHub zoals je deed met onderstaande. Liefst ook het onderscheid maken tussen bugs (dit werkt niet) en improvements (dit kan beter) of extra features (dit mist nog).

Ik heb ze voorlopig even op Google Docs gezet voor het gemak https://docs.google.com/spreadsheets/d/1Nnt0RJsqNnw-cmT8Hnu6aZd1-FMUUoAvHR_hPtmkrYI/edit?usp=sharing

Vriendelijke groeten,
Thimo

---

Van: Maes Dominic
Verzonden: donderdag 17 september 2015 16:02
Aan: oSoc15/educal
CC: Bernaert Ann; Thoeye Thimo
Onderwerp: RE: [educal] Cannot add users to my organization (403) (#78)

Hi Thimo,

Ondertussen heb ik de fout al gevonden. Ik probeerde een (test-)user aan te maken met een mailadres dat hij al kende voor een andere school.
Dat is dus correct gedrag, alleen had ik graag een boodschap gehad om dit te melden op het scherm.

Bijgevoegd een hele lijst van defects die ik gevonden heb tijdens mijn eerste testen.

Mvgr,
Dominic

Van: tthoeye [mailto:notifications@github.com]
Verzonden: donderdag 17 september 2015 15:52
Aan: oSoc15/educal
CC: Maes Dominic
Onderwerp: Re: [educal] Cannot add users to my organization (403) (#78)

Thx, I tried with chrome/win but have no problem adding a user. Could you please provide some details (username, school and password) so I can try to reproduce. Also, it would help if you can provide us with the console output (ctrl-shift-i) in Chrome

##

**Comment by dmadigipolis** [comment]
Dag Dominic.

Nee, de laatste commit die online staat is die op tthoeye/educal. Ik update asap.

Grt

-------- Original message --------
From: Maes Dominic
Date:18/09/2015 7:51 AM (GMT+01:00)
To: Thoeye Thimo ,oSoc15/educal
Cc: Bernaert Ann ,Rosseau Bart
Subject: RE: [educal] Cannot add users to my organization (403) (#78)

Hoi Thimo,

Ik zie dat Bertware al wat bevindingen in Github heeft gestoken/opgelost.
Is de nieuwe versie beschikbaar op educal.open.gent?

D.

-----Oorspronkelijk bericht-----
Van: Thoeye Thimo
Verzonden: donderdag 17 september 2015 16:24
Aan: Maes Dominic; oSoc15/educal
CC: Bernaert Ann; Rosseau Bart
Onderwerp: RE: [educal] Cannot add users to my organization (403) (#78)

Heel erg bedankt Dominic,
Ik hoop dat je hier niet te veel tijd in hebt moeten steken.

Ik wil zeker nog eens door deze uitgebreide lijst gaan, maar het zou wel handig zijn als je de issues zou rapporteren in GitHub zoals je deed met onderstaande. Liefst ook het onderscheid maken tussen bugs (dit werkt niet) en improvements (dit kan beter) of extra features (dit mist nog).

Ik heb ze voorlopig even op Google Docs gezet voor het gemak https://docs.google.com/spreadsheets/d/1Nnt0RJsqNnw-cmT8Hnu6aZd1-FMUUoAvHR_hPtmkrYI/edit?usp=sharing

Vriendelijke groeten,
Thimo

---

Van: Maes Dominic
Verzonden: donderdag 17 september 2015 16:02
Aan: oSoc15/educal
CC: Bernaert Ann; Thoeye Thimo
Onderwerp: RE: [educal] Cannot add users to my organization (403) (#78)

Hi Thimo,

Ondertussen heb ik de fout al gevonden. Ik probeerde een (test-)user aan te maken met een mailadres dat hij al kende voor een andere school.
Dat is dus correct gedrag, alleen had ik graag een boodschap gehad om dit te melden op het scherm.

Bijgevoegd een hele lijst van defects die ik gevonden heb tijdens mijn eerste testen.

Mvgr,
Dominic

Van: tthoeye [mailto:notifications@github.com]
Verzonden: donderdag 17 september 2015 15:52
Aan: oSoc15/educal
CC: Maes Dominic
Onderwerp: Re: [educal] Cannot add users to my organization (403) (#78)

Thx, I tried with chrome/win but have no problem adding a user. Could you please provide some details (username, school and password) so I can try to reproduce. Also, it would help if you can provide us with the console output (ctrl-shift-i) in Chrome
