### ISSUE TITLE
No way to reorder calendars

### ISSUE THREAD

**Issue by Bertware** [oSoc15/educal#84]
Newest is at the bottom.
Implementing re-ordering is difficult, sorting alphabetically might be a temporary fix.

**Comment by tthoeye** [comment]
@dmadigipolis alphabetical ordering okay?

**Comment by dmadigipolis** [comment]
Yep; Lijkt me ok

Van: tthoeye [mailto:notifications@github.com]
Verzonden: vrijdag 18 september 2015 10:34
Aan: oSoc15/educal
CC: Maes Dominic
Onderwerp: Re: [educal] No way to reorder calendars (#84)

@dmadigipolishttps://github.com/dmadigipolis alphabetical ordering okay?

**Comment by tthoeye** [comment]
Tested, calendars are sorted alphabetically. Please close the issue.

**Comment by dmadigipolis** [comment]
Tested. Ok to close.
