### ISSUE TITLE
Critical: adding events removes oldest ones

### ISSUE THREAD

**Issue by Bertware** [oSoc15/educal#87]
From @dmadigipolis:

```
Programeren van periode over maandeinde heen loopt fout.
Hier is tot 4 december gepland, maar wordt maar tot 3 december getoond.
Bovendien, als ik iets bijplan  op 3 december, verdwijnt de periode uit de kalender. (en omgekeerd) 

Ernstig probleem: Tevens verdwijnt 3 december input na ingave van input op 18 december
(is er een maximum aantal events?)

BLOCKING ISSUE!!!!!
Bijplannen van zaken doet de laatst ingevoerde verdwijnen.
Indien periodes, wordt de laatste dag ervan niet getoond.
Blijkbaar worden alle periodes niet correct getoond (meer dan één dag)
```

**Comment by tthoeye** [comment]
Moeilijk te reproduceren:
- Programmeren over maandeinde lukt
- Als er een periode over meerdere dagen wordt ingepland wordt dat goed opgeslagen maar de laatste dag wordt niet ingekleurd in de kalender (tenzij het einduur uitdrukkelijk wordt opgenomen én na 9u 's ochtends valt)
- Periode verdwijnt: cannot reproduce
- _Ernstig probleem_ er is geen maximum aantal events. Deze bug kan ik niet reproduceren, kan dit nogmaals getest worden?

Voorstel om de issue te hernoemen naar _Last day of period isn't displayed in calendar when end hour is not set after 9 AM_

**Comment by tthoeye** [comment]
**Correctie**

Laatste event op een dag verdwijnt inderdaad bij inplannen van een nieuw evenement!! Ik splits de issue op.

**Comment by tthoeye** [comment]
This happens after removing an event. The ID of the removed event is somehow kept in the session and fed to the API when creating a new event, this leading it to believe that this is an update.

**Comment by tthoeye** [comment]
We should probably put these last changes (set active.ev.id to 0)) in the close() function...
