### ISSUE TITLE
Google calendar remains empty after importing ics

### ISSUE THREAD

**Issue by Bertware** [oSoc15/educal#88]

**Comment by Bertware** [comment]
Tried importing .ics file, worked as expected.
@digipolis / @tthoeye : can someone reproduce? make sure you're on the latest version

**Comment by tthoeye** [comment]
I can import the .ICS file without any problems, both in Outlook and Google Calendar

**Comment by dmadigipolis** [comment]
Retested: Lijkt te werken nu. (nieuwe bug toegevoegd)
