### ISSUE TITLE
Ics All export not working

### ISSUE THREAD

**Issue by dmadigipolis** [oSoc15/educal#90]
I have downloaded the ICS from edugo-lourdes-meerhout (all).

I see events that are not in the calendar, but must be coming from another calender:  Ma14/9 12:45/14:45 tekenles. 14/9 8:00 / 9:00 Laravel Class.....

**Comment by Bertware** [comment]
Can you try the fix on the develop branch?

**Comment by tthoeye** [comment]
@dmadigipolis I've tracked the develop branch on http://educal.open.gent, so you can test there.

As for this bug, I'm getting an exception when exporting my calendars (see image)

![exportcalendar](https://cloud.githubusercontent.com/assets/1484581/10053500/be48eaa2-622c-11e5-8884-7734f53ded45.png)

**Comment by dmadigipolis** [comment]
Hoi Thimo,

Juist even gekeken.
Klopt genereert een error (trying to get property of non-object)

Plus de knop ‘exporteer’ lijkt niet van de eerste keer te werken…. (weinig reactie)

D.

Van: tthoeye [mailto:notifications@github.com]
Verzonden: woensdag 23 september 2015 19:55
Aan: oSoc15/educal
CC: Maes Dominic
Onderwerp: Re: [educal] The ICS contains events from another calendar. (#90)

@dmadigipolishttps://github.com/dmadigipolis I've tracked the develop branch on http://educal.open.gent, so you can test there.

As for this bug, I'm getting an exception when exporting my calendars (see image)

[exportcalendar]https://cloud.githubusercontent.com/assets/1484581/10053500/be48eaa2-622c-11e5-8884-7734f53ded45.png

**Comment by tthoeye** [comment]
Sorry @Bertware moeten fixen op tthoeye/master branch. oSoC15/develop gaf nog problemen.

**Comment by Bertware** [comment]
No problem, glad that it's fixed now! :)
